#!/bin/bash

if [[ -f  c-build-tools/subInfo ]]; then
	source c-build-tools/subInfo
else
	source subInfo
fi

if [[ -f version ]];then
	source version
fi
versionNum="${#ALLVERSION[@]}"
EXCLUDEVERSION=""
num=0

for ver in ${ALLVERSION[@]}
do
	#將現在版本從所有版本中過濾掉
	if [ $ver != $EXTRACTVERSION ]; then
		if [[ $num == $((0)) ]]; then
			EXCLUDEVERSION="$ROOTDIR/$ver"
		else
			EXCLUDEVERSION+=" $ROOTDIR/$ver"
		fi
		num=$((num+1))
	fi
done

if [[ -n "$EXCLUDEVERSION" ]]; then
	EXCLUDEVERSION="-path ${EXCLUDEVERSION// / -o -path }"
fi



