#!/bin/bash

if [[ -f  c-build-tools/subInfo ]]; then
	source c-build-tools/subInfo
else
	source subInfo
fi

rootPath=`pwd`

submoduleArray=( $gitSubmoduleDIR )
branchName=$1

#git checkout $branchName
git $1 $2 $3 $4 $5
for element in "${submoduleArray[@]}"; do
	cd $rootPath
	cd $element
	echo "In submodule $(basename $element)"
	#git checkout $branchName
	git $1 $2 $3 $4 $5
done
