#!/bin/bash

if [[ -f  c-build-tools/subInfo ]]; then
	source c-build-tools/subInfo
else
	source subInfo
fi

sourcelist="source.mk"

if [[ -n "$SUBMODULEDIR" ]]; then
	SUBDIR="-path ${SUBMODULEDIR// / -o -path }"
	echo "SUBDIR = $SUBDIR" > $sourcelist
fi

if [[ -z "$SUBDIR" ]]; then
	SOUCE_ELE=$(find $ROOTDIR -name "*.cpp" -printf "%P ")
	SOURCE=$(basename -a $SOUCE_ELE | sort | xargs echo)
	SOURCEPATH=$(find $ROOTDIR -name "*.cpp" -print| sort  | xargs echo)
else
	SOUCE_ELE=$(find $ROOTDIR \( $SUBDIR \) -a -prune -o -name "*.cpp" -printf "%P ")
	SOURCE=$(basename -a $SOUCE_ELE | sort | xargs echo)
	SOURCEPATH=$(find $ROOTDIR \( $SUBDIR \) -a -prune -o -name "*.cpp" -print | sort | xargs echo)
fi

echo -e "SOURCE = $SOURCE" > $sourcelist
echo -e "SOURCEPATH = $SOURCEPATH" >> $sourcelist

echo -e "SUBMODULEDIR = $SUBMODULEDIR" >> $sourcelist
echo -e "SUBMODULELOC = $SUBMODULELOC" >> $sourcelist
echo -e "SUBMODULE = $SUBMODULE" >> $sourcelist

