#!/bin/bash

ROOTDIR="."

SUBMODULEDIR=$(dirname $(find . \( -path *.git \) -a -prune -o -name src -a -not -path ./src -printf "%P ") | xargs echo)
SUBMODULELOC=$(dirname $(find . \( -path *.git \) -a -prune -o -name src -a -not -path ./src -printf "%P ") | xargs -i echo -L{} | xargs echo)
SUBMODULE=$(basename -a $(dirname `find . \( -path *.git \) -a -prune -o -name src -a -not -path ./src -print`) | xargs -i echo -l{} | xargs echo)

if [[ -n "$SUBMODULEDIR" ]]; then
	SUBDIR="-path ./${SUBMODULEDIR// / -o -path .\/}"
	echo "SUBDIR = $SUBDIR" > sourcelist
fi

if [[ -z "$SUBDIR" ]]; then
	echo -e "SOURCE = $(find $ROOTDIR -name "*.cpp" -printf "%f "|xargs echo)" > sourcelist

	echo -e "SOURCEPATH = $(find $ROOTDIR -name "*.cpp" -print|xargs echo)" >> sourcelist
else
	echo -e "SOURCE = $(find $ROOTDIR \( $SUBDIR \) \
		-a -prune -o -name "*.cpp" -printf "%f "|xargs echo)" >> sourcelist

	echo -e "SOURCEPATH = $(find $ROOTDIR \( $SUBDIR \) \
		-a -prune -o -name "*.cpp" -print|xargs echo)" >> sourcelist
fi

# echo -e "DIR =  `dirname $(find $ROOTDIR -name "*.cpp" -printf "%P ") | sort | uniq | xargs echo`" >> sourcelist

echo -e "SUBMODULEDIR = $SUBMODULEDIR" >> sourcelist
echo -e "SUBMODULELOC = $SUBMODULELOC" >> sourcelist
echo -e "SUBMODULE = $SUBMODULE" >> sourcelist

