#!/bin/bash

ROOTDIR="src"

#Use for recongizing submodules.
IDENTITY="makefile"

submoduleResult=$(find -L $ROOTDIR \( -path *.git \) -a -prune -o -name $IDENTITY -a -not -path $ROOTDIR -a -not -path "*c-build-tools/*" -a -not -path "*test/*" -printf "%p ")

if [[ -n "$submoduleResult" ]]; then
	SUBMODULEDIR=$(dirname $submoduleResult | sort | xargs echo)
	SUBMODULELOC=$(dirname $submoduleResult | xargs -i echo -L{} | sort | xargs echo)
	SUBMODULE=$(basename -a $(dirname $submoduleResult) | xargs -i echo -l{} | sort | xargs echo)
fi


#Identify real git module for script gitFunction and gitk.
gitSubmodule=$(dirname $(find $ROOTDIR -name ".git" -printf "%p ") | sort | xargs echo)