#!/bin/bash

ROOTDIR="src"

#Use for recongizing submodules.
IDENTITY="makefile"

submoduleResult=$(find $ROOTDIR \( -path *.git \) -a -prune -o -name $IDENTITY -a -not -path $ROOTDIR -printf "%p ")

SUBMODULEDIR=$(dirname $submoduleResult | xargs echo)
SUBMODULELOC=$(dirname $submoduleResult | xargs -i echo -L{} | xargs echo)
SUBMODULE=$(basename -a $(dirname $submoduleResult) | xargs -i echo -l{} | xargs echo)
